import importlib


def test_domain_packages_are_importable():
    modules = [
        "app.common.security",
        "app.domains",
        "app.domains.developer",
        "app.domains.developer.service.indexing_service",
        "app.domains.developer.controller.admin_router",
        "app.domains.auth",
        "app.domains.auth.models",
        "app.domains.auth.repository.auth_repository",
        "app.domains.auth.controller.auth_router",
        "app.domains.auth.schema.auth_schemas",
        "app.domains.auth.service.auth_service",
        "app.domains.classroom.controller.teacher_class_router",
        "app.domains.classroom.controller.student_class_router",
        "app.domains.progress.controller.teacher_student_router",
        "app.domains.classroom.dependency.classroom_dependencies",
        "app.domains.classroom.models",
        "app.domains.classroom.repository.classroom_repository",
        "app.domains.classroom.service.classroom_service",
        "app.domains.classroom.schema.classroom_schemas",
        "app.domains.agent.schema.agent_schemas",
        "app.domains.agent.service.agent_service",
        "app.domains.instruction.controller.student_router",
        "app.domains.instruction.controller.teacher_router",
        "app.domains.instruction.service.generation",
        "app.domains.instruction.validation",
        "app.domains.instruction.models",
        "app.domains.instruction.repository.assignment_repository",
        "app.domains.instruction.schema.instruction_schemas",
        "app.domains.instruction.service.instruction_service",
        "app.domains.content.controller.catalog_router",
        "app.domains.content.stage1.router",
        "app.domains.content.stage1.schemas",
        "app.domains.content.stage1.service",
        "app.domains.content.stage2.router",
        "app.domains.content.stage2.schemas",
        "app.domains.content.stage2.service",
        "app.domains.progress.controller.student_progress_router",
        "app.domains.content.stage3.router",
        "app.domains.content",
        "app.domains.content.models",
        "app.domains.content.repository.catalog_repository",
        "app.domains.content.schema.catalog_schemas",
        "app.domains.content.service.catalog_service",
        "app.domains.progress.models",
        "app.domains.progress.repository.learning_record_repository",
        "app.domains.progress.schema.learning_record_schemas",
        "app.domains.progress.service.learning_record_service",
        "app.domains.content.stage3.schemas",
        "app.domains.content.stage3.service",
        "app.domains.agent",
        "app.domains.agent.controller.agent_router",
        "app.domains.agent.schema.agent_schemas",
        "app.infrastructure.rag",
        "app.infrastructure.rag.retriever",
        "app.infrastructure.rag.schemas",
        "app.infrastructure.rag.service",
        "app.infrastructure.db.mongo.indexes",
    ]

    for module_name in modules:
        assert importlib.import_module(module_name)
